name: Terraform Apply

on:
  push:
    branches: [ main ]

permissions:
  id-token: write     
  contents: read

env:
  AWS_REGION: ${{ secrets.AWS_REGION }}
  TF_VAR_ovh_application_key: ${{ secrets.OVH_APPLICATION_KEY }}
  TF_VAR_ovh_application_secret: ${{ secrets.OVH_APPLICATION_SECRET }}
  TF_VAR_ovh_consumer_key: ${{ secrets.OVH_CONSUMER_KEY }}

jobs:
  terraform-apply:
    runs-on: ubuntu-latest
    environment:
      name: prod

    steps:
      - name: Checkout repo
        uses: actions/checkout@v4

      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v4
        with:
          role-to-assume: ${{ secrets.AWS_ROLE_TO_ASSUME }}
          aws-region: ${{ env.AWS_REGION }}

      - name: Setup Terraform
        uses: hashicorp/setup-terraform@v3
        with:
          terraform_version: 1.9.5

      - name: Terraform Init
        run: terraform init -input=false

      - name: Terraform Plan
        shell: bash
        run: |
          set -e
          set -o pipefail
          terraform plan -input=false -no-color -out=tfplan.bin | tee plan.txt

      - name: Terraform Apply
        shell: bash
        run: |
          set -e
          terraform apply -auto-approve tfplan.bin
