name: Terraform Basic Check

on:
  pull_request:
    branches: [ main ]
    paths:
      - "**/*.tf"
      - ".terraform.lock.hcl"

jobs:
  validate:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repo
        uses: actions/checkout@v4

      - name: Setup Terraform
        uses: hashicorp/setup-terraform@v3
        with:
          terraform_version: 1.9.5

      - name: Terraform Init (bez backendu)
        run: terraform init -backend=false -input=false

      - name: Terraform Fmt
        run: terraform fmt -check -recursive

      - name: Terraform Validate
        run: terraform validate
